version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.2
  aws-s3: circleci/aws-s3@4.0.0
  node: circleci/node@5.2.0

jobs:
  deploy:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "${AWS_OIDC_ROLE_ARN}"
          region: "${AWS_REGION}"
          profile_name: "OIDC"
      - node/install-packages
      - run:
          command: "npm run build"
          name: "Build application"
      - aws-s3/sync:
          arguments: --delete
          from: "dist/"
          to: "s3://${AWS_BUCKET}/"
          profile_name: "OIDC"

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
          context:
            - AWS
